[2024-05-13T14:09:15.923+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-13T14:09:15.967+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: students.extract manual__2024-05-13T14:09:13.324504+00:00 [queued]>
[2024-05-13T14:09:15.999+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: students.extract manual__2024-05-13T14:09:13.324504+00:00 [queued]>
[2024-05-13T14:09:16.001+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-13T14:09:16.054+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2024-05-13 14:09:13.324504+00:00
[2024-05-13T14:09:16.077+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=889) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-13T14:09:16.080+0000] {standard_task_runner.py:63} INFO - Started process 891 to run task
[2024-05-13T14:09:16.081+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'students', 'extract', 'manual__2024-05-13T14:09:13.324504+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/students.py', '--cfg-path', '/tmp/tmp9nilccdu']
[2024-05-13T14:09:16.085+0000] {standard_task_runner.py:91} INFO - Job 214: Subtask extract
[2024-05-13T14:09:16.202+0000] {task_command.py:426} INFO - Running <TaskInstance: students.extract manual__2024-05-13T14:09:13.324504+00:00 [running]> on host c2025ffc2c56
[2024-05-13T14:09:16.375+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='students' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-05-13T14:09:13.324504+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-13T14:09:13.324504+00:00'
[2024-05-13T14:09:16.378+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-13T14:09:16.379+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-13T14:09:16.379+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/students.py", line 17, in extract
    filenames = os.listdir(source_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags\\playground\\source'
[2024-05-13T14:09:16.397+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=students, task_id=extract, run_id=manual__2024-05-13T14:09:13.324504+00:00, execution_date=20240513T140913, start_date=20240513T140915, end_date=20240513T140916
[2024-05-13T14:09:16.418+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 214 for task extract ([Errno 2] No such file or directory: 'opt/airflow/dags\\playground\\source'; 891)
[2024-05-13T14:09:16.460+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-13T14:09:16.486+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-13T14:09:16.490+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
