[2024-05-13T14:54:09.667+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-13T14:54:09.700+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: students.load scheduled__2024-05-13T14:52:00+00:00 [queued]>
[2024-05-13T14:54:09.714+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: students.load scheduled__2024-05-13T14:52:00+00:00 [queued]>
[2024-05-13T14:54:09.715+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-13T14:54:09.736+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2024-05-13 14:52:00+00:00
[2024-05-13T14:54:09.746+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1632) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-13T14:54:09.749+0000] {standard_task_runner.py:63} INFO - Started process 1634 to run task
[2024-05-13T14:54:09.749+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'students', 'load', 'scheduled__2024-05-13T14:52:00+00:00', '--job-id', '279', '--raw', '--subdir', 'DAGS_FOLDER/students.py', '--cfg-path', '/tmp/tmpqfas_z_f']
[2024-05-13T14:54:09.754+0000] {standard_task_runner.py:91} INFO - Job 279: Subtask load
[2024-05-13T14:54:09.838+0000] {task_command.py:426} INFO - Running <TaskInstance: students.load scheduled__2024-05-13T14:52:00+00:00 [running]> on host c2025ffc2c56
[2024-05-13T14:54:10.056+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='students' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-05-13T14:52:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-13T14:52:00+00:00'
[2024-05-13T14:54:10.059+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-13T14:54:10.065+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-13T14:54:10.066+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/students.py", line 41, in load
    f.write(f"{o['id']},{o['name']}\n")
               ~^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-05-13T14:54:10.089+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=students, task_id=load, run_id=scheduled__2024-05-13T14:52:00+00:00, execution_date=20240513T145200, start_date=20240513T145409, end_date=20240513T145410
[2024-05-13T14:54:10.113+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 279 for task load (string indices must be integers, not 'str'; 1634)
[2024-05-13T14:54:10.165+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-13T14:54:10.190+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-13T14:54:10.193+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
