[2024-05-19T12:14:59.398+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T12:14:59.426+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dummyjson_products.write_to_csv manual__2024-05-19T12:14:50.853468+00:00 [queued]>
[2024-05-19T12:14:59.439+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dummyjson_products.write_to_csv manual__2024-05-19T12:14:50.853468+00:00 [queued]>
[2024-05-19T12:14:59.440+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-19T12:14:59.462+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): write_to_csv> on 2024-05-19 12:14:50.853468+00:00
[2024-05-19T12:14:59.471+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3800) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T12:14:59.473+0000] {standard_task_runner.py:63} INFO - Started process 3802 to run task
[2024-05-19T12:14:59.473+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dummyjson_products', 'write_to_csv', 'manual__2024-05-19T12:14:50.853468+00:00', '--job-id', '1637', '--raw', '--subdir', 'DAGS_FOLDER/dummyjson_product.py', '--cfg-path', '/tmp/tmp5jfe5_cv']
[2024-05-19T12:14:59.477+0000] {standard_task_runner.py:91} INFO - Job 1637: Subtask write_to_csv
[2024-05-19T12:14:59.539+0000] {task_command.py:426} INFO - Running <TaskInstance: dummyjson_products.write_to_csv manual__2024-05-19T12:14:50.853468+00:00 [running]> on host ca927d78a9ea
[2024-05-19T12:14:59.707+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='fathurrahmanhernanda@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dummyjson_products' AIRFLOW_CTX_TASK_ID='write_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-05-19T12:14:50.853468+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-19T12:14:50.853468+00:00'
[2024-05-19T12:14:59.711+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T12:14:59.735+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T12:14:59.736+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dummyjson_product.py", line 52, in write_to_csv_generic
    writer.writerow(product)
  File "/usr/local/lib/python3.12/csv.py", line 164, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/csv.py", line 157, in _dict_to_list
    wrong_fields = rowdict.keys() - self.fieldnames
                   ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'
[2024-05-19T12:14:59.751+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dummyjson_products, task_id=write_to_csv, run_id=manual__2024-05-19T12:14:50.853468+00:00, execution_date=20240519T121450, start_date=20240519T121459, end_date=20240519T121459
[2024-05-19T12:14:59.769+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1637 for task write_to_csv ('str' object has no attribute 'keys'; 3802)
[2024-05-19T12:14:59.809+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-19T12:14:59.870+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T12:14:59.873+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
