[2024-05-19T12:43:36.706+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T12:43:36.769+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_products_from_api.extract_and_write_to_csv scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-05-19T12:43:36.789+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_products_from_api.extract_and_write_to_csv scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-05-19T12:43:36.790+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-05-19T12:43:36.854+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_and_write_to_csv> on 2024-05-01 00:00:00+00:00
[2024-05-19T12:43:36.876+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4498) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T12:43:36.880+0000] {standard_task_runner.py:63} INFO - Started process 4513 to run task
[2024-05-19T12:43:36.890+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'extract_products_from_api', 'extract_and_write_to_csv', 'scheduled__2024-05-01T00:00:00+00:00', '--job-id', '1755', '--raw', '--subdir', 'DAGS_FOLDER/dummyjson_product.py', '--cfg-path', '/tmp/tmpeh7zt6sm']
[2024-05-19T12:43:36.898+0000] {standard_task_runner.py:91} INFO - Job 1755: Subtask extract_and_write_to_csv
[2024-05-19T12:43:37.090+0000] {task_command.py:426} INFO - Running <TaskInstance: extract_products_from_api.extract_and_write_to_csv scheduled__2024-05-01T00:00:00+00:00 [running]> on host ca927d78a9ea
[2024-05-19T12:43:37.381+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_products_from_api' AIRFLOW_CTX_TASK_ID='extract_and_write_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-01T00:00:00+00:00'
[2024-05-19T12:43:37.386+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T12:43:38.125+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T12:43:38.132+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dummyjson_product.py", line 26, in extract_products_and_write_to_csv
    with open("/path/to/products.csv", "w", newline="") as csvfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/products.csv'
[2024-05-19T12:43:38.171+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_products_from_api, task_id=extract_and_write_to_csv, run_id=scheduled__2024-05-01T00:00:00+00:00, execution_date=20240501T000000, start_date=20240519T124336, end_date=20240519T124338
[2024-05-19T12:43:38.216+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1755 for task extract_and_write_to_csv ([Errno 2] No such file or directory: '/path/to/products.csv'; 4513)
[2024-05-19T12:43:38.244+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-19T12:43:38.292+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T12:43:38.305+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
