[2024-05-16T09:27:09.988+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T09:27:10.071+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: randomuser_ingestion.is_api_available scheduled__2024-05-01T11:00:00+00:00 [queued]>
[2024-05-16T09:27:10.148+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: randomuser_ingestion.is_api_available scheduled__2024-05-01T11:00:00+00:00 [queued]>
[2024-05-16T09:27:10.155+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-16T09:27:10.383+0000] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-05-01 11:00:00+00:00
[2024-05-16T09:27:10.567+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=170) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-16T09:27:10.678+0000] {standard_task_runner.py:63} INFO - Started process 196 to run task
[2024-05-16T09:27:10.670+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'randomuser_ingestion', 'is_api_available', 'scheduled__2024-05-01T11:00:00+00:00', '--job-id', '1021', '--raw', '--subdir', 'DAGS_FOLDER/randomuser_ingestion.py', '--cfg-path', '/tmp/tmp37tlm089']
[2024-05-16T09:27:10.727+0000] {standard_task_runner.py:91} INFO - Job 1021: Subtask is_api_available
[2024-05-16T09:27:11.356+0000] {task_command.py:426} INFO - Running <TaskInstance: randomuser_ingestion.is_api_available scheduled__2024-05-01T11:00:00+00:00 [running]> on host 8d1d9b6df744
[2024-05-16T09:27:12.037+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='randomuser_ingestion' AIRFLOW_CTX_TASK_ID='is_api_available' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-01T11:00:00+00:00'
[2024-05-16T09:27:12.048+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T09:27:12.050+0000] {baseoperator.py:399} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-05-16T09:27:12.052+0000] {http.py:137} INFO - Poking: /api
[2024-05-16T09:27:12.074+0000] {base.py:84} INFO - Using connection ID 'randomuser_api' for task execution.
[2024-05-16T09:27:13.505+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-05-16T09:27:13.523+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T09:27:13.584+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=randomuser_ingestion, task_id=is_api_available, run_id=scheduled__2024-05-01T11:00:00+00:00, execution_date=20240501T110000, start_date=20240516T092710, end_date=20240516T092713
[2024-05-16T09:27:13.722+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-16T09:27:13.785+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-16T09:27:13.797+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
